[package]
name = "argsparse"
description = "Yet another simple (and naive) argument parser"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/goncalompontes/argsparse"
version = "0.1.2"
edition = "2024"

[dependencies]
